### ISSUE TITLE
Sometimes fails at print_tree

### ISSUE THREAD

**Issue by ksunden** [wright-group/bluesky-in-a-box#28]
Some scans with constants fail at print_tree, despite working perfectly fine when you open the data after the fact to print the tree.

Because saving of the print tree happens before plotting, plots are not generated when this occurs.

My suspicion is that it may for some reason have to do with constants that refer to variables not otherwise in the scan, but not fully sure...

The data is otherwise recorded properly and works fine when you plot it manually.

@kelsonoram can you copy the stack trace into a comment here?

**Comment by kelsonoram** [comment]
This is the error message that bluesky-in-a-box-wt5-1 gives for this print_tree issue:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/numexpr/necompiler.py", line 735, in getArguments

    a = local_dict[name]

KeyError: 'hp'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run

    self._context.run(self._callback, *self._args)

  File "/usr/local/lib/python3.10/site-packages/bluesky/run_engine.py", line 2446, in process

    exceptions = self.cb_registry.process(name, name.name, doc)

  File "/usr/local/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 379, in process

    func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 468, in __call__

    return mtd(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/event_model/__init__.py", line 113, in __call__

    return self._dispatch(name, doc, validate)

  File "/usr/local/lib/python3.10/site-packages/event_model/__init__.py", line 121, in _dispatch

    output_doc = getattr(self, name)(doc)

  File "//./wt5_event_model.py", line 218, in stop

    self.data[name].print_tree(verbose=True)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_data.py", line 1337, in print_tree

Skipping key 'versions' from start document in metadata because it cannot be placed in HDF5 attrs

    self._print_branch("", depth=0, verbose=verbose)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_data.py", line 268, in _print_branch

    print_leaves(prefix, self.constants)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_data.py", line 259, in print_leaves

    s = prefix + a + b + "{0}: {1}".format(i, item._leaf)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_constant.py", line 55, in _leaf

    out += " = {0}".format(self.value)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_constant.py", line 81, in value

    return np.nanmean(self.masked)

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_axis.py", line 180, in masked

    arr = self[:]

  File "/usr/local/lib/python3.10/site-packages/WrightTools/data/_axis.py", line 64, in __getitem__

    return numexpr.evaluate(self.expression.split("=")[0], local_dict=vs)

  File "/usr/local/lib/python3.10/site-packages/numexpr/necompiler.py", line 811, in evaluate

    arguments = getArguments(names, local_dict, global_dict)

  File "/usr/local/lib/python3.10/site-packages/numexpr/necompiler.py", line 737, in getArguments

    a = global_dict[name]

KeyError: 'hp'

**Comment by ksunden** [comment]
Thanks @kelsonoram
